services:
  http-checker:
    image: ghcr.io/theshamuel/hhchecker:1.0
    build: .
    hostname: http-health-checker
    container_name: http-health-checker
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "2"
    environment:
      - TZ=Europe/Dublin
      - URL
      - MAX_ALERTS
      - TIMEOUT
      - EMAIL_ENABLED
      - EMAIL_FROM
      - EMAIL_TO
      - EMAIL_CC
      - EMAIL_SUBJECT
      - EMAIL_TEXT
      - EMAIL_MAILGUN_API_URL
      - EMAIL_MAILGUN_API_KEY
      - TELEGRAM_ENABLED
      - TELEGRAM_BOT_API_KEY
      - TELEGRAM_CHANNEL_ID
      - TELEGRAM_MESSAGE
      - DEBUG